### ISSUE TITLE
cannot remove an existing file

### ISSUE THREAD

**Issue by ouyuyuan** [NCAR/ncl#100]
an existing file cann't be remove

var = new( (/300,720,1440/), "integer")
newvar = var
; test.nc will no be removed if it already exist
system("rm -f test.nc")

OS: Linux (Centos 7.4)
OS version
Linux basic 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
NCL version: 6.6.2  ( install with conda)

**Comment by rbrownrigg** [comment]
Hi,

Its hard to imagine this is an NCL issue. I just ran a quick test
successfully on my own system, and was able to delete a preexisting file.
Are you getting an error message? Are the permissions on the file correct,
are you running the NCL script from the correct directory, etc?

Rick

**Comment by ouyuyuan** [comment]
There is no error message. But if I create a new file "test.nc", NCL will fail, saying it cann't create that file. I do have the permission on the file. I can delete it in bash, and can "touch " it in bash.
This problem is quite odd. If I delete the "newvar = var" statement, everything is OK. Or, if I change the dimension to a smaller size, say, 300 to 30, it works too. If I run this script on another machine, like my Mac OS, it works fine. I also try the NCL 6.3.0 version from yum on the same Centos OS with this script, the problem remains. So I guess this problem is combination of OS and NCL.

**Comment by ouyuyuan** [comment]
This problem is half-solved. It seems like a memory problem ( though I use "unlimit " command at .bashrc ). NCL can delete preexisting file now if I delete some variable, say the "newvar" in the above script, before the "system" command.
