### ISSUE TITLE
Corrupted Debian build environment?

### ISSUE THREAD

**Issue by mjskier** [NCAR/ncl#104]
**Describe the bug**
On a Debian 8 system, the ncl executable in ncl_ncarg-6.6.2-Debian8.11_64bit_gnu492.tar.gz depends on libiconv.so.2
There is no such library available on Debian 8 as the functionality of that library has been moved into libc6.

**Provide the following:**
 Try to run ncl, it fails to start with 

`error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory`

**Computing environment**
 - OS: Linux
 - OS version: Debian 8
 - NCL Version: 6.6.2
 - Installation method: binary from NCAR website

**Additional context**
I was able to at least run ncl by removing the dependency:

`patchelf --remove-needed libiconv.so.2 ncl`

**Comment by pilotchute** [comment]
If a similar issue is encountered in the future, `conda update --all -c conda-forge` should solve the problem.
