### ISSUE TITLE
Shared library missing after a fresh install from conda-forge

### ISSUE THREAD

**Issue by senesis** [NCAR/ncl#109]
After having installed Ncl through conda from conda-forge , I cannot launch it; I get that error
`ncl: error while loading shared libraries: libtiledb.so.1.6.0: cannot open shared object file: No such file or directory`
Is there some dependency missing in conda configuration for Ncl ?

**Computing environment** 
  - Ubuntu 16.04
 - NCL Version: 6.6.2

**Comment by senesis** [comment]
And the trick suggested in #104 (i.e. using patchelf) doesn't work in my case

**Comment by khallock** [comment]
Hi @senesis, could you please run `conda list` with your NCL environment activated and reply with the output? Based on the error message you observed, I suspect there is a dependency conflict somewhere.

Also, you could try running `conda update --all -c conda-forge` (with your NCL environment activated) to see if that resolves any potential dependency issues.

I hope this helps!

**Comment by senesis** [comment]
The `update --all` command did the job. Thanks a lot
