### ISSUE TITLE
Using qsort in a user defined function

### ISSUE THREAD

**Issue by chrisbskinner** [NCAR/ncl#13]
Hi,

I was using the qsort routine in a user-defined function and got an unexpected result. I've replicated it here with a simple example using ncl 6.4.0:

Example Script "test_qsort_infunction.ncl"
*********************************************
load "my_lib.ncl"    ;this is where I store my simple user-defined function "sort_test"

begin
a = (/10, 9, 8, 7, 6, 5, 4, 3, 2, 1/)
print(a)

c = sort_test(a)
print(c)

print(a)
end

Example Function "sort_test"
******************************
undef("sort_test")
function sort_test(array)

begin
qsort(array)

b = array
return(b)
end

-------------------------

When I run the ncl script "test_qsort_infunction.ncl" I get the following output:

Copyright (C) 1995-2017 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.4.0
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details

Variable: a
Type: integer
Total Size: 40 bytes
            10 values
Number of Dimensions: 1
Dimensions and sizes:	[10]
Coordinates: 
(0)	10
(1)	9
(2)	8
(3)	7
(4)	6
(5)	5
(6)	4
(7)	3
(8)	2
(9)	1

Variable: c
Type: integer
Total Size: 40 bytes
            10 values
Number of Dimensions: 1
Dimensions and sizes:	[10]
Coordinates: 
(0)	1
(1)	2
(2)	3
(3)	4
(4)	5
(5)	6
(6)	7
(7)	8
(8)	9
(9)	10

Variable: a
Type: integer
Total Size: 40 bytes
            10 values
Number of Dimensions: 1
Dimensions and sizes:	[10]
Coordinates: 
(0)	1
(1)	2
(2)	3
(3)	4
(4)	5
(5)	6
(6)	7
(7)	8
(8)	9
(9)	10

-------------------------

Perhaps this is already known and expected, but I didn't expect the user-defined function to influence the order of the a array within my script (ie, it sorted the a values, but I didn't want it to). 

- Chris

**Comment by khallock** [comment]
Hi Chris,

While this behavior can be confusing, it is intended. [NCL uses "pass-by-reference" parameters](https://www.ncl.ucar.edu/Document/Manuals/Ref_Manual/NclVariables.shtml#Parameters), meaning that modifications made to a parameter inside a function/procedure will propagate back to the original variable (in the scope where the function/procedure was originally called).

In your sort_test function, if you copy `array` to another variable `b` before running qsort, and then call `qsort(b)`, the function will return the sorted array without modifying the original "array" variable:
```
undef("sort_test")
function sort_test(array)

begin
b = array
qsort(b)

return(b)
end
```
I hope this helps,
Kevin

**Comment by chrisbskinner** [comment]
Good to know. Thank you Kevin.

Best,
Chris
