### ISSUE TITLE
How to convert a string into a variable

### ISSUE THREAD

**Issue by Geek-007** [NCAR/ncl#131]
I have customized a function that requires input variables for calculation, but this variable has certain rules, I want to read it in a loop, for example：

;
data_a=(/2,3,4/)
data_b=(/1,2,3/)
data_c=(2,1,1)
abbr_plt=(/"a","b","c"/)
do np=0,2
;function cal(input:numeric)
result=cal("data_"+abbr_plt(np))
end do

operation error:
fatal:Argument type mismatch on argument (0) of (cal) can not coerce

If it works that way, it works:
result=cal(data_a)
result=cal(data_b)
result=cal(data_c)

**Comment by KMFleischer** [comment]
Hi QingQing,

the argument of the function cal is not a string (numeric) but you give 
a string.
What do you want to do?
What is cal looking like?

You can't do calculations on strings.

-Karin

Am 05.05.20 um 05:53 schrieb QingQing Tong:

**Comment by Geek-007** [comment]
Thank you for your answer.
You're right, can't do calculations on strings.

I want to change the name of the variable in a circular way, and the result is changed to a string. Now I just want to convert the string to a variable.

**Comment by rbrownrigg** [comment]
So-called "string references" might do what you want:

http://ncl.ucar.edu/Document/Manuals/Ref_Manual/NclVariables.shtml#StringRef

However, it looks like they only apply to attribute and coordvar names, and
variables on filevarsb, but not to stand-alone variable names (at least, I
couldn't make it work). Something like this works:

hostvar = True
hostvar@data_a=(/2,3,4/)
hostvar@data_b=(/1,2,3/)
hostvar@data_c=(/2,1,1/)
abbr_plt=(/"a","b","c"/)
do np=0,2
    att = "data_"+abbr_plt(np)
    print(hostvar@$att$)
end do

Rick

**Comment by Geek-007** [comment]
Thanks for your answer, this is a good idea
