### ISSUE TITLE
how to get time series for a subarea of shapefile

### ISSUE THREAD

**Issue by amalsalhi** [NCAR/ncl#15]

**Comment by marylhaley** [comment]
For questions on NCL usage, please use the ncl-talk email list:

http://www.ncl.ucar.edu/Support/email_lists.shtml

Github issues should be used for reporting bugs or contributing code. 

For some NCL shapefile examples, see the shapefiles examples page:

http://www.ncl.ucar.edu/Applications/shapefiles.shtml

There are several examples showing how to mask data.

**Comment by amalsalhi** [comment]
i used shapefile_11.ncl but it gives me a variable 2D, how could i add the
time dimension please.
the script i used in the attachement

Il giorno gio 29 nov 2018 alle ore 16:35 Mary Haley <
notifications@github.com> ha scritto:

**Comment by amalsalhi** [comment]
ok sorry

Il giorno gio 29 nov 2018 alle ore 18:57 Mary Haley <
notifications@github.com> ha scritto:
