### ISSUE TITLE
systemfunc_ncl reading nc files 

### ISSUE THREAD

**Issue by cicy996** [NCAR/ncl#156]
Dear all,

I am trying to readingsome netcdf files. These files names are 191001_20191015, 191001_20191016, ...  191001_20191029.
When I code    _files = systemfunc("ls "+diri+"191001_201910[15:29].nc")_
It will print 191001_20191010, 191001_20191011, ... 191001_20191029.
So please help me how to choose the files from number 15 to 29.

Thank you very much!
Chang

**Comment by forgetmenot9911** [comment]
try this:
`import glob`
`file=glob.glob(r'191001_201910[15:29].nc')`
`for f in file:`

**Comment by cicy996** [comment]
> try this:
> `import glob`
> `file=glob.glob(r'191001_201910[15:29].nc')`
> `for f in file:`

Thanks for your reply.
But really sorry that I used ncl rather than python to read files.

**Comment by cicy996** [comment]
> try this:
> `import glob`
> `file=glob.glob(r'191001_201910[15:29].nc')`
> `for f in file:`

**Comment by forgetmenot9911** [comment]
omg,I didn't notice,sry

**Comment by cicy996** [comment]
> omg,I didn't notice,sry

ok. I public issue on the website first time.  I don't know why I close the issue and how to reopen it.  sad

**Comment by Dave-Allured** [comment]
Solved:
https://mailman.ucar.edu/pipermail/ncl-talk/2021-April/018077.html

**Comment by cicy996** [comment]
> Solved:
> https://mailman.ucar.edu/pipermail/ncl-talk/2021-April/018077.html

Thanks a lot. This issue got solved.
