### ISSUE TITLE
Error cannot find -lgrib2c 

### ISSUE THREAD

**Issue by afernandezody** [NCAR/ncl#162]
Hello,
When I try to build NCL from source with GRIB2 support, it is generating the error message `/bin/ld: cannot find -lgrib2c`. It seems like the discrepancy is because the libraries created with the newest versions of g2clib-devel use different names. Is this simply a legacy problem and a matter of making the necessary changes in the source code, or am I missing something else? Thanks.

**Comment by rbrownrigg** [comment]
I'm not sure what you mean by "different names". The message indicates
simply that the library can not be found, and either it doesn't exist on
your system, or you'll need an appropriate -L directive to point to the
directory where the library resides.  If names have changed in source code,
then I would think you'd be getting "unresolved symbol" types of messages.

**Comment by afernandezody** [comment]
Yes, the problem is that it doesn't find the library because in my system (CentOS8), the name of the library seems to be `libg2c_v1.6.0.a`, not `libgrib2c` as the NCL installer seeks. I'm not sure if in other systems the library is built with a different name, and my question is simply if the issue is simply a matter of notation of if there is anymore to it that I might be missing. Thanks.

**Comment by rbrownrigg** [comment]
I understand now. Perhaps a symlink of libgrib2c.a to the longer name?

**Comment by afernandezody** [comment]
Either that or modify the source files so that it looks for the other name. Just wanted to double-check that I'm not missing anything. Thanks.
