### ISSUE TITLE
Issues while processing the fontcaps

### ISSUE THREAD

**Issue by coderodyhpc** [NCAR/ncl#175]
Hello,
My compilation of the fontcaps has been causing me problems as it causes a segmentation fault. After tinkering with it for some time, it seems that I might have gotten a better idea of where things go awry. It builds `fontc` but while processing font1 (or any other font), it produces the segmentation fault error. Backtracing the error points out to GBYTES in gsbytes.C and, more specifically, to the line:
`		lb = ((~(MASK << qb)) & (*(p + j))) << jb;
`
I usually code in Fortran and my C is basic, so I have no clue why building libncarg_c.a doesn't signal any issue (have gone over it several times) but processing the fonts results in something pointing to a false memory address. Any suggestion would be more than welcomed as I really don't know what to try next.
On a minor note, I have another Q: do `fontc` and `font1...` should reside in the fontcap subdirectory or at ncl/bin?
Thanks.     
P.S. The compiler is GCC-11.2 but I also tried GCC-8 with the same result.

**Comment by chen-shaoheng** [comment]
Hello, do you have any solution to this problem now?
