### ISSUE TITLE
ncl executable absent in conda installation on Mac silicon

### ISSUE THREAD

**Issue by ipisso** [NCAR/ncl#214]
After installing ncl via conda using the recommneded procedure, the installation completes without error messages but the executable ncl is absent 

(ncl_stable):~ user$ echo $NCARG_ROOT
/Users/user/miniconda3/envs/ncl_stable
(ncl_stable):~ user$ ncl -V
-bash: ncl: command not found

(ncl_stable):~ user$ ls /Users/user/miniconda3/envs/ncl_stable/bin/nc
nc-config         ncargf90          ncargversion      nccopy            ncgm2cgm          ncl_grib2nc       
ncargcc           ncargfile         ncargworld        ncdump            ncgmstat          ncl_quicklook     
ncargex           ncargpath         ncarlogo2ps       ncgen             ncl_convert2nc    ncurses6-config   
ncargf77          ncargrun          ncarvversion      ncgen3            ncl_filedump      ncursesw6-config  

**Provide the following:**
 - a concise NCL script demonstrating the issue (remove unnecessary code)

invoking ncl fails

**Computing environment**
 - OS: Sonoma on Mac M3
 - OS version: [e.g. Ubuntu 16.04, MacOS 10.13.6, Windows 10]
 - NCL Version: 6.6.2 
 - Installation method: conda

**Comment by kafitzgerald** [comment]
Unfortunately, there's not a working osx-arm64 build at this point. 

More info and current status here: https://github.com/conda-forge/ncl-feedstock/issues/134

Closing this as a duplicate.
