### ISSUE TITLE
Document the deprecated WRF-NCL routines

### ISSUE THREAD

**Issue by marylhaley** [NCAR/ncl#40]
With the new WRF routines added in this release, some WRF routines will still be available but will be deprecated. They need to be documented as such:

http://www.ncl.ucar.edu/Document/Functions/WRF_arw/wrf_user_ll_to_ij.shtml
http://www.ncl.ucar.edu/Document/Functions/WRF_arw/wrf_user_ij_to_ll.shtml
http://www.ncl.ucar.edu/Document/Functions/WRF_arw/wrf_user_intrp2d.shtml
http://www.ncl.ucar.edu/Document/Functions/WRF_arw/wrf_user_intrp3d.shtml

**Comment by marylhaley** [comment]
With the new WRF routines added in this release, some existing WRF routines will still be available but will be deprecated.

**Comment by marylhaley** [comment]
I'm reassigning this to Bill so he can review the deprecated routines documentation. The only thing added was some "deprecated" type of text in the synopsis and at the beginning of the description section.

**Comment by bladwig1** [comment]
Looks good to me.
