### ISSUE TITLE
questions about the external directory

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ncl#75]
One of the top-level subdirectories is "external". It is not built if --disable-ncl is used, so it seems to contian libraries only used by ncl. Is that correct?

This directory contains:

```
  /home/ed/ncl/external:
  total used in directory 228 available 170912236
  drwxrwxr-x 11 ed ed   4096 Feb 21 07:42 .
  drwxrwxr-x 15 ed ed   4096 Feb 21 07:42 ..
  drwxrwxr-x  3 ed ed  12288 Feb 21 07:42 blas
  drwxrwxr-x  3 ed ed  12288 Feb 21 07:42 fftpack5_dp
  drwxrwxr-x  2 ed ed   4096 Feb  4 14:56 g2clib-1.2.1
  drwxrwxr-x  2 ed ed   4096 Feb  4 14:56 g2clib-1.2.3
  drwxrwxr-x  2 ed ed   4096 Feb  4 14:56 g2clib-1.4.0
  drwxrwxr-x  2 ed ed   4096 Feb  4 14:56 g2clib-1.5.0
  drwxrwxr-x  2 ed ed   4096 Feb  4 14:56 g2clib-1.6.0
  -rw-rw-r--  1 ed ed     22 Feb  4 14:56 .gitignore
  drwxrwxr-x  3 ed ed 110592 Feb 21 07:42 lapack
  -rw-rw-r--  1 ed ed  20737 Feb 21 07:42 Makefile
  -rw-rw-r--  1 ed ed    105 Feb 14 15:10 Makefile.am
  -rw-rw-r--  1 ed ed  18694 Feb 19 13:46 Makefile.in
  drwxrwxr-x  3 ed ed  12288 Feb 21 07:42 sphere3.1_dp
  -rw-rw-r--  1 ed ed    653 Feb  4 14:56 yMakefile

```

The yMakefile has this:

`SUBDIRS = blas lapack sphere3.1_dp  fftpack5_dp
`

Some questions:
* Are these libraries available as separate packages? That is, is there a blas package that can be installed to obviate the need for blas in the external directory?
* What are the g2clib directories? They don't seem to be used by the build. Perhaps they should be removed.
* Do we want to install the resulting libraries as separate libraries? Or are we content to leave them uninstalled and just have ncl link to them?

Any other information anyone would like to share about what's happening in the external directory would be very welcome.

**Comment by rbrownrigg** [comment]
I don't really know the history of these libraries and how they came to be
bundled with the NCL source. fftpack and spherepack were developed at NCAR:

    https://en.wikipedia.org/wiki/FFTPACK
    https://www2.cisl.ucar.edu/resources/legacy/spherepack/documentation

And of course blas and lapack exist in the wild, and could in principle be
installed dependencies. However, I would not be surprised if there were
versioning issues/dependencies.

I am confused about g2clib. There is the following note in the instructions
for building NCL from source:

    http://ncl.ucar.edu/Download/build_from_src.shtml#g2clib

However, yes I agree, looking through the build, I can't see where it gets
built nor is referenced by any of the source modules (?)

To your third question -- my personal preference would be to leave these
libraries as they are and just link against them. Unbundling them is likely
going to be the proverbial "several steps sideways just to go one step
forward" :-/

**Comment by edhartnett** [comment]
OK, awesome, that's very helpful.

You have been used to thinking that a gzip of the development build is what the user will get, but under autotools, that's not what will happen. Instead, automake will construct a distribution tarball which will include everything the user gets.

So currently, the g2clib directories will not be in the user distribution (because automake does not need them to build the code). 

If these are unused, they should be deleted from the git repo. Recall that deleting it from the repo just removes it from future branches. Of course nothing is really deleted and it always lives on in the repo.

**Comment by edhartnett** [comment]
Thanks for the answers. I am going to close this ticket.
