### ISSUE TITLE
Are the many .gitignore files in the repo intentional?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ncl#76]
There are many .gitignore files in the repo. Is this intentional?

```
 find . -name .gitignore
./ncarview/src/bin/.gitignore
./ni/src/lib/hlu/.gitignore
./ni/src/lib/nio/.gitignore
./ni/src/ncl/.gitignore
./ni/src/nyacc/.gitignore
./ni/src/scripts/.gitignore
./ni/src/db/rgb/.gitignore
./ni/src/mkwrap/.gitignore
./common/src/bin/ncargpath/.gitignore
./common/src/fontcap/.gitignore
./common/src/graphcap/.gitignore
./common/src/libncarg_c/.gitignore
./install/install/.gitignore
./ngmath/src/bin/nnalg/.gitignore
./ngmath/src/lib/.gitignore
./config/.gitignore
./external/.gitignore
./ncarg2d/src/bin/ezmapdemo/.gitignore
./ncarg2d/src/bin/.gitignore
./ncarg2d/src/libncarg/conpack/.gitignore
./ncarg2d/src/libncarg/Iftran/.gitignore
./ncarg2d/src/libncarg/ezmapa/.gitignore
./ncarg2d/src/libncarg/ezmap/.gitignore
./ncarg2d/src/libncarg/softfill/.gitignore
./ncarg2d/src/libncarg/areas/.gitignore
./ncarg2d/src/libncarg/plotchar/.gitignore
./ncarg2d/src/libncarg/pwritx/.gitignore
./ncarg2d/src/libncarg/conpackt/.gitignore
./ncarg2d/src/libncarg/vaspackt/.gitignore
./ncarg2d/src/libncarg/polypack/.gitignore
./ncarg2d/src/libncarg_gks/cdrivers/.gitignore
./ncarg2d/src/db/pwritxnt/.gitignore
./ncarg2d/src/db/ezmap/.gitignore
./ncarg2d/src/db/plotchar/.gitignore
./ncarg2d/src/debugging/VisAreaMapTool/.gitignore
./.gitignore
```

**Comment by khallock** [comment]
Hi @edhartnett, when we migrated from SVN to git, I chose to create multiple .gitignore files in order to prevent a single root-level .gitignore from becoming too bloated.

Ideally, I would want a global .gitignore to be at least somewhat readable and to not contain entries for hundreds of specific files, although there's no reason why such a .gitignore wouldn't work.

In the spirit of "open development", this is the sort of issue that we should be listening to external collaborators about. Would you find it easier to deal with a single root-level .gitignore?

**Comment by edhartnett** [comment]
I would suggest one .gitignore for the whole project. I don't think it matters if it is particularly readable, no one reads it anyway. ;-)

I am not going to mess with them - I just brought it up because it looks odd.

**Comment by khallock** [comment]
> I would suggest one .gitignore for the whole project. I don't think it matters if it is particularly readable, no one reads it anyway. ;-)

That's a great point... None of the .gitignore files have even been touched since August 2016, so apparently _we_ don't even look at these files very often.

 
> You might also consider one in each top-level directory.
> 
> I am not going to mess with them - I just brought it up because it looks odd.

That sounds good to me. I'll leave this issue open for now so that it can possibly be addressed in the future.

Thanks for your input!

**Comment by edhartnett** [comment]
I'm going to close this issue since there is no work taking place and I'm not intended to do this. When you are interested in this issue, you can re-open it.
