### ISSUE TITLE
example ep_flux2.ncl

### ISSUE THREAD

**Issue by markcollier** [NCAR/ncl#86]
![epflux 20161207_20161207](https://user-images.githubusercontent.com/11568716/54167389-8c029d00-44bd-11e9-8ee7-047cb18247d1.png)
I have tried using epflux_2.ncl using daily mean ncep2 data sourced from e.g. ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2.dailyavgs/pressure/vwnd.2016.nc

so I have change "dir" to point to my input directory. The script appears to pick up the correct single day. In order to get the plotting part to complete without error I need to change:
1. switch off 
;    res_vec@vcRefMagnitudeF       = 200               ; add a reference vector
;    res_vec@vcRefLengthF          = 0.05              ; what the ref length is

and 

;      res_con@cnLevelSpacingF        = 200.        ; Contour level Spacing

however, the result (attached) does not compare to the one given on the NCL page:

http://www.ncl.ucar.edu/Applications/Images/epflux_2_lg.png

switching off the attributes above allows the arrays to be plotted, however, the values themselves are not matching the expected range in the example plot. The original script may read in ncep v1 data, however, this could not explain the fundamental problem of wrong EP flux diagnostics.

I have tried running it on several machines, producing the same result. My main machine is described by:

(ncl_stable) col414@oa-35-cdc:/OSM/CBR/OA_DCFP/work/col414/cafepp$ ncl -V
6.5.0
(ncl_stable) col414@oa-35-cdc:/OSM/CBR/OA_DCFP/work/col414/cafepp$ uname -a
Linux oa-35-cdc 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux

I'm wondering if this is an anomalous or consistent with and out of date or erroneous example script? My examination of units and coordinates would suggest that the epflux function inputs are O.K.

I have been trying to apply this function to MERRA-2 daily data without success, so I thought it would be wise to try and regenerate the example result.

Any help appreciated.

Regards, Mark.

**Comment by rbrownrigg** [comment]
Hi Mark,

I really don't have an answer to your question. I downloaded the data from
the link you sent, and I got errors about vector/contour values being
inappropriate. I noted that your link was to the reanalysis2 collection. I
downloaded the comparable files from the reanalysis1 collection, and the
script worked out of the box, producing the plot we see on the web site.

I then did this:
printMinMax(reanalysis1->uwnd,True)
(0)
(0)     mean Daily U-wind (m/s) : min=-117   max=133.2

printMinMax(reanalysis2->uwnd,True)
(0)
(0)     daily mean 6-hourly U-wind on Pressure Levels (m/s) : min=-28980
max=-5739

I don't know what this implies, other than its not a surprise that
magnitudes and contour-intervals in the original script are not appropriate
for the reanalysis2 data.

You likely know all this already, but I hope it helps...
Rick

**Comment by markcollier** [comment]
Hi Rick, yes ncep2 has the data represented by shorts, so after unpacking it seems to work.
I'll keep trying with merra-2, surely if the inputs are similar then it should work, I have a few leads to exhaust e.g. ncep has land points filled whereas merra-2 are set to missing.
Cheers

**Comment by rbrownrigg** [comment]
HI Mark,

I did not notice the shorts/offset/scale thing -- good eye.  I understand
why files are encoded like that from an  engineering point of view, but
I've often thought that's a booby-trap to users of the data. Perhaps the
file readers should automatically unpack the data when encountering
offset/scale attributes on a variable, unless the user takes explicit steps
to prevent that.

FWIW...
Rick
