### ISSUE TITLE
not able to run ncl_filedump command

### ISSUE THREAD

**Issue by dhaneeshimd** [NCAR/ncl#98]
I'm not able to run ncl_filedump command on grib2 or any other data formats. Used to get the following error:
/bin/csh: bad interpreter: No such file or directory
As suggested from another website where the same error was discussed, I ran the following command:
sudo apt-get install csh

Now, after installing cshell also the problem is not solved. The following error is coming now.

(ncl_stable) dhaneesh@dhaneesh-Inspiron-N4010:~$ ncl_filedump gfs_4_20180731_0000_000.grb2
Segmentation fault (core dumped)

 - OS: Linux
 - OS version: Ubuntu 18.04.2 LTS
 - NCL Version: 6.6.2
 - Installation method: Used binary from NCAR website for NCL 6.5 and conda for NCL 6.6.2
But the problem remains.

**Comment by rbrownrigg** [comment]
Hi,

This is the second issue we've seen this week involving the combination of
ncl_filedump, Ubuntu 18.04, and SEGVs. We are unable to replicate the
problem and currently don't have convenient access to an Ubuntu system. We
will need to spin up an Ubuntu VM, as time permits, and try to track this
down. I wish I had a better answer for you...

Rick

**Comment by dhaneeshimd** [comment]
Hi Rick,
Thank you so much for answering. So, that means if I try another OS like another version of ubuntu ncl_filedump will work?

Dhaneesh

**Comment by rbrownrigg** [comment]
The other person who reported this problem stated that things work fine
with Ubuntu 15.04.  I can't guarantee anything. My CentOS was able to open
the files. We haven't had any reports involving other OSes. My suspicion is
that 18.04 has an incompatible shared library, but I've not been able to
verify that.

**Comment by dhaneeshimd** [comment]
I installed CentOs 7. Now I'm able to run ncl_filedump and other commands.
Thanks.

**Comment by Chen-yang-JIN** [comment]
when using ncl_filedump with mac mini m4, it shows
dyld[6675]: missing symbol called
Abort

So how can I solve this problem.
