### ISSUE TITLE
https://www.ncl.ucar.edu/Document/Manuals/NCL_User_Guide/Data/albedo_a_curvilinear.nc not there

### ISSUE THREAD

**Issue by jamessong** [NCAR/ncl#99]
**Describe the bug**
A clear and concise description of what the bug is. Include any error messages.

**Provide the following:**
 - a concise NCL script demonstrating the issue (remove unnecessary code)
 - necessary data files
 - relevant graphical output

**Computing environment**
 - OS: [Linux, Mac, or Windows]
 - OS version: [e.g. Ubuntu 16.04, MacOS 10.13.6, Windows 10]
 - NCL Version: [e.g. 6.5.0]
 - Installation method: [binary from NCAR website, conda, other package manager (apt, brew, macports, yum), built from source]

**Additional context**

**Comment by dennisshea** [comment]
Karin Meier-Fleischer [DKRZ] has made the file available at:
**https://nextcloud.dkrz.de/s/r8eBjcL2ZkmRF2R**
